app:
    name: containedenv
    user: cteuser

profiles:
    containedenv:
        user: cteuser
    github:
        user: cteuser
        token: "0000-0000"   

projects:
    all:
        requires:
            - git
            - vim
            
    containedenv:
        sources:
            - https://github.com/adamferreira/containedenv.git
        scmprofile: github
        
